{{- if not .Values.sentry.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-secret
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "{{ if .Values.hooks.removeOnSuccess }}hook-succeeded,{{ end }}before-hook-creation"
    "helm.sh/hook-weight": "3"
type: Opaque
data:
  key: {{ randAlphaNum 50 | b64enc | quote }}
{{- end -}}